print "^D - get out of python"
print "mkdir - make directory"
print "cd (some directory) - change directory"
print "print - like 'cout' in c++"
print "# to make a comment"
print " + add, - subtract, * multiplt, / divide, "
print "%" 'as a math operarator, gives remainder, also used for string formatting\n with 'd' as digit, 'f' as float, 's' as string, '
print "> greater than, < less than, <= less than or equal, >= greater than or equal"
print "= to assign a value, == to test if two values are equal"
print "raw_input(prompt,variable,etc.) - like cin in c++"
print "argv - argument values"
print "script - the actual text"
print "close - closes a file, read - reads a file(can assign the result to a variable\n readline - reads one line of text, truncate - empties a file, write() - write things to a file"
